#!/bin/bash
#File: auto_merge.sh


for branch in $(git branch | cut -c 3-); do 
   if [ "$branch" != "master" ]; then 
    git checkout $branch 

     # Compile the code
        ./compile.sh
        
        cd ./tests
        # Run tests
        ./runTests ${branch}-suite.txt ../prog
       
        # Check if both compile and tests are successful
        if [ $? -eq 0 ]; then
            # Try to merge with master
            git checkout master
            git merge --no-commit --no-ff $branch >/dev/null 2>&1
           
            # Check if merge is successful
            if [ $? -eq 0 ]; then
                git commit -m "Merged $branch into master" >/dev/null 2>&1
            else
                # Abort merge if conflicts
                git merge --abort >/dev/null 2>&1
            fi
        fi

        cd ..
    fi
done
